### ISSUE TITLE
Can I create a report from the logs?

### ISSUE THREAD

**Issue by serge-stotskiy** [exakat/exakat#125]
Hi, I have a big project, about 7000 files. A day goes to check. Usually the project hung, through the docker container the logs all were created, but the report was not formed.

**Comment by exakat** [comment]
You can use the dir_ignore directive to omit some of the files and directories. This will bring down the number of files and you'll get the audit faster, though partial. 

One classic performance recommendation is to give a lot of memory to Java. 
'export JAVA_OPTIONS='-Xms1024m -Xmx6096m'; or 'setenv JAVA_OPTIONS='-Xms1024m -Xmx6096m'
We use 16Gb on a bare metal installation, and 32 with docker containers, and everything works. 

Several improvement in speed were added to Exakat since last year, so a try with the current version will help.
